get_tus_options: handle HTTP errors

diff --git a/bin/tus b/bin/tus
--- a/bin/tus
+++ b/bin/tus
@@ -81,16 +81,25 @@ function join { local IFS="$1"; shift
 # ==============================================================================
 # tus
 
-function tus_options {
+function get_tus_options {
   # The Client SHOULD NOT include the Tus-Resumable header in the request and the Server MUST ignore the header.
   local header_args=()
   set_header_args "${TUS_HEADERS[@]}"
-  curl -s \
+  local response
+  local rc
+  response="$(curl -s \
     --fail-with-body \
     "${header_args[@]}" \
     --head \
     --request OPTIONS \
-    "$TUSD" | grep '^Tus-' | tr -d '\r'
+    "$TUSD"
+  )"
+  rc=$?
+  if [ $rc != 0 ]; then
+    echo "$response" | tr -d '\r'
+    return $rc
+  fi
+  echo "$response" | grep '^Tus-' | tr -d '\r'
 }
 
 function tus_supports {
@@ -273,7 +282,12 @@ if [ $OPT_DEBUG = 1 ]; then
 fi
 
 [ -z "$TUSD" ] && error 'tusd endpoint' 'TUSD'
-readarray -t TUS_OPTIONS <<<"$(tus_options)"
+if ! tus_options="$(get_tus_options)"; then
+  echo "error: failed to get TUS options:"
+  echo "$tus_options"
+  exit 1
+fi
+readarray -t TUS_OPTIONS <<<"$tus_options"
 if [ "$OPT_OPTIONS" = 1 ]; then
   echo -e "\033[1;34m➤ $TUSD ☁\033[0m\n\033[2m⌄\033[0m"
   if [ ${#TUS_OPTIONS[@]} = 0 ]; then
